### ISSUE TITLE
check if settings file exist

### ISSUE THREAD

**Issue by iricigor** [iricigor/WTS1#4]

**Comment by iricigor** [comment]
@MangyCoyote what do you think should be proper action if the file does not exist?
I guess for testing purposes we can create it? Or, prompt user to select some alternative json file?

**Comment by MangyCoyote** [comment]
This app is named "Windows Terminal Settings (Editor)". I think nonexisting JSON file in most cases mean prerequisite (WT) has not been installed.

So unless we change an app to be more generic I would propose to actually verify if WT has been installed at all. If installed, query for JSON path (if that is something we can get).

If we still can not find the file, than what is the meaning of this app? Either prompt user to find it or (my suggestion) warn the user with a suggestion on what is wrong and how can he/she fix it and exit an app.
